# config.yml
rss_feeds:
  https://kubernetes.io/feed.xml:
    name: Kubernetes
    category: PLATFORM
  https://aws.amazon.com/blogs/devops/feed/:
    name: AWS DevOps
    category: CLOUD
  https://cloudplatform.googleblog.com/feeds/posts/default:
    name: Google Cloud
    category: CLOUD
  https://devblogs.microsoft.com/devops/feed/:
    name: Azure DevOps
    category: CLOUD
  https://github.blog/feed/:
    name: GitHub
    category: TOOLS

manual_sources:
  - name: ChatGPT Updates
    url: https://help.openai.com/en/articles/6825453-chatgpt-release-notes
    category: AI
  - name: Claude Updates
    url: https://www.anthropic.com/news
    category: AI

categories:
  - SECURITY
  - FEATURE
  - PERFORMANCE
  - DEPRECATION

impact_levels:
  - HIGH
  - MEDIUM
  - LOW

# Number of high-impact updates to feature in highlights
max_highlights: 3

# Minimum impact level to include in digest (HIGH, MEDIUM, or LOW)
minimum_impact: LOW
