# List of RSS feeds to monitor for DevOps updates
rss_feeds:
  - "https://github.blog/changelog/feed/"         # GitHub Changelog
  - "https://aws.amazon.com/new/feed/"            # AWS What's New
  - "https://cloud.google.com/feeds/announcements.xml"  # Google Cloud Announcements
  - "https://azure.microsoft.com/en-us/updates/feed/"  # Azure Updates

# List of manual sources that require web scraping
manual_sources:
  - url: "https://example.com/manual-source1"
    title: "Example Manual Source 1"
    provider_name: "Example Provider 1"
  - url: "https://example.com/manual-source2"
    title: "Example Manual Source 2"
    provider_name: "Example Provider 2"
