<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DevOps Weekly Update</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-50">
    <div class="max-w-6xl mx-auto px-4 py-8">
        <!-- Header -->
        <header class="text-center mb-12">
            <h1 class="text-4xl font-bold text-gray-900 mb-2">DevOps Weekly Update</h1>
            <p class="text-xl text-gray-600">{{ week_range }}</p>
        </header>

        <!-- High Impact Updates -->
        {% if high_impact %}
        <section class="mb-12">
            <div class="flex items-center mb-6">
                <h2 class="text-2xl font-bold text-red-600">🚨 High Impact Updates</h2>
            </div>
            <div class="grid gap-6 md:grid-cols-2">
                {% for entry in high_impact %}
                <div class="bg-white rounded-lg shadow-lg overflow-hidden border-l-4 border-red-500">
                    <div class="p-6">
                        <div class="flex justify-between items-start mb-4">
                            <h3 class="text-xl font-semibold text-gray-900">{{ entry.title }}</h3>
                            <span class="px-2 py-1 text-sm bg-red-100 text-red-800 rounded-full">{{ entry.provider_name }}</span>
                        </div>
                        <div class="prose">
                            <p class="text-gray-600 mb-4">{{ entry.analysis.summary }}</p>
                            {% if entry.analysis.key_changes %}
                            <div class="mb-4">
                                <h4 class="font-semibold text-gray-900 mb-2">Key Changes:</h4>
                                <ul class="list-disc pl-5 space-y-1">
                                    {% for change in entry.analysis.key_changes %}
                                    <li class="text-gray-600">{{ change }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                            {% endif %}
                            {% if entry.analysis.action_items %}
                            <div class="mb-4">
                                <h4 class="font-semibold text-gray-900 mb-2">Action Items:</h4>
                                <ul class="list-disc pl-5 space-y-1">
                                    {% for item in entry.analysis.action_items %}
                                    <li class="text-gray-600">{{ item }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                            {% endif %}
                            <div class="mt-4 flex flex-wrap gap-2">
                                {% for tag in entry.analysis.tags %}
                                <span class="px-2 py-1 text-sm bg-gray-100 text-gray-600 rounded-full">{{ tag }}</span>
                                {% endfor %}
                            </div>
                            <a href="{{ entry.link }}" class="inline-block mt-4 text-blue-600 hover:text-blue-800">Read more →</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>
        {% endif %}

        <!-- Medium Impact Updates -->
        {% if medium_impact %}
        <section class="mb-12">
            <div class="flex items-center mb-6">
                <h2 class="text-2xl font-bold text-yellow-600">⚠️ Medium Impact Updates</h2>
            </div>
            <div class="grid gap-6 md:grid-cols-2">
                {% for entry in medium_impact %}
                <div class="bg-white rounded-lg shadow-lg overflow-hidden border-l-4 border-yellow-500">
                    <div class="p-6">
                        <div class="flex justify-between items-start mb-4">
                            <h3 class="text-lg font-semibold text-gray-900">{{ entry.title }}</h3>
                            <span class="px-2 py-1 text-sm bg-yellow-100 text-yellow-800 rounded-full">{{ entry.provider_name }}</span>
                        </div>
                        <p class="text-gray-600 mb-4">{{ entry.analysis.summary }}</p>
                        <div class="mt-4 flex flex-wrap gap-2">
                            {% for tag in entry.analysis.tags %}
                            <span class="px-2 py-1 text-sm bg-gray-100 text-gray-600 rounded-full">{{ tag }}</span>
                            {% endfor %}
                        </div>
                        <a href="{{ entry.link }}" class="inline-block mt-4 text-blue-600 hover:text-blue-800">Read more →</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>
        {% endif %}

        <!-- Low Impact Updates -->
        {% if low_impact %}
        <section>
            <div class="flex items-center mb-6">
                <h2 class="text-2xl font-bold text-blue-600">ℹ️ Other Updates</h2>
            </div>
            <div class="grid gap-4">
                {% for entry in low_impact %}
                <div class="bg-white rounded-lg shadow p-4 border-l-4 border-blue-500">
                    <div class="flex justify-between items-start">
                        <h3 class="text-lg font-semibold text-gray-900">{{ entry.title }}</h3>
                        <span class="px-2 py-1 text-sm bg-blue-100 text-blue-800 rounded-full">{{ entry.provider_name }}</span>
                    </div>
                    <p class="text-gray-600 mt-2">{{ entry.analysis.summary }}</p>
                    <a href="{{ entry.link }}" class="inline-block mt-2 text-blue-600 hover:text-blue-800">Read more →</a>
                </div>
                {% endfor %}
            </div>
        </section>
        {% endif %}

        <!-- Footer -->
        <footer class="mt-12 text-center text-gray-600">
            <p>Generated on {{ week_range }}</p>
        </footer>
    </div>
</body>
</html>
