# config.yml

# RSS feeds for DevOps tool updates
rss_feeds:
  # Terraform Core and Providers
  "https://github.com/hashicorp/terraform/releases.atom":
    name: "Terraform CLI"
    importance_keywords:
      - "BREAKING CHANGE"
      - "security fix"
      - "vulnerability"
  
  "https://github.com/hashicorp/terraform-provider-google/releases.atom":
    name: "GCP Provider"
    importance_keywords:
      - "BREAKING CHANGE"
      - "deprecation"
      
  "https://github.com/hashicorp/terraform-provider-azurerm/releases.atom":
    name: "Azure Provider"
    importance_keywords:
      - "BREAKING CHANGE"
      - "deprecation"

  # Platform Status and Updates
  "https://www.githubstatus.com/history.atom":
    name: "GitHub Status"
    importance_keywords:
      - "outage"
      - "degraded performance"
      
  "https://status.hashicorp.com/history.atom":
    name: "HashiCorp Status"
    importance_keywords:
      - "outage"
      - "degraded performance"
      
  "https://github.blog/changelog/feed/":
    name: "GitHub Changelog"
    importance_keywords:
      - "security"
      - "actions"
      - "api"
      
  "https://cloud.google.com/feeds/gcp-terraform-release-notes.xml":
    name: "GCP Terraform Updates"
    importance_keywords:
      - "breaking"
      - "security"
      - "feature"

  "https://github.com/terraform-docs/terraform-docs/releases.atom":
    name: "terraform-docs"
    importance_keywords:
      - "BREAKING CHANGE"
      - "security"

# Manual sources requiring web scraping
manual_sources:
  - name: "ChatGPT Updates"
    url: "https://help.openai.com/en/articles/6825453-chatgpt-release-notes"
    type: "webpage"
    
  - name: "Claude Updates"
    url: "https://www.anthropic.com/news"
    type: "webpage"
    
  - name: "Azure DevOps Updates"
    url: "https://learn.microsoft.com/en-us/azure/devops/release-notes/"
    type: "webpage"

# Conference and event tracking configuration
conferences:
  sources:
    - "https://www.hashicorp.com/events"      # HashiConf and other HashiCorp events
    - "https://cloud.google.com/next"         # Google Cloud Next
    - "https://www.microsoft.com/en-us/ignite"  # Microsoft Ignite
