# config.yml

# RSS feeds for DevOps tool updates
rss_feeds:
  # Terraform Core and Providers
  "https://github.com/hashicorp/terraform/releases.atom":
    provider_name: "terraform"
    importance_keywords:
      - "BREAKING CHANGE"
      - "security fix"
      - "vulnerability"
  
  "https://github.com/hashicorp/terraform-provider-google/releases.atom":
    provider_name: "terraform"
    importance_keywords:
      - "BREAKING CHANGE"
      - "deprecation"
      
  "https://github.com/hashicorp/terraform-provider-azurerm/releases.atom":
    provider_name: "terraform"
    importance_keywords:
      - "BREAKING CHANGE"
      - "deprecation"

  # Platform Status and Updates
  "https://www.githubstatus.com/history.atom":
    provider_name: "github"
    importance_keywords:
      - "outage"
      - "degraded performance"
      
  "https://status.hashicorp.com/history.atom":
    provider_name: "hashicorp"
    importance_keywords:
      - "outage"
      - "degraded performance"
      
  "https://github.blog/changelog/feed/":
    provider_name: "github"
    importance_keywords:
      - "security"
      - "actions"
      - "api"
      
  "https://cloud.google.com/feeds/gcp-terraform-release-notes.xml":
    provider_name: "google"
    importance_keywords:
      - "breaking"
      - "security"
      - "feature"

  "https://github.com/terraform-docs/terraform-docs/releases.atom":
    provider_name: "terraform"
    importance_keywords:
      - "BREAKING CHANGE"
      - "security"

# Manual sources requiring web scraping
manual_sources:
  - provider_name: "openai"
    url: "https://help.openai.com/en/articles/6825453-chatgpt-release-notes"
    type: "webpage"
      
  - provider_name: "anthropic"
    url: "https://www.anthropic.com/news"
    type: "webpage"
      
  - provider_name: "azuredevops"
    url: "https://learn.microsoft.com/en-us/azure/devops/release-notes/"
    type: "webpage"

# Conference and event tracking configuration
conferences:
  sources:
    - "https://www.hashicorp.com/events"      # HashiConf and other HashiCorp events
    - "https://cloud.google.com/next"         # Google Cloud Next
    - "https://www.microsoft.com/en-us/ignite"  # Microsoft Ignite
