name: DevOps News Aggregator

on:
  schedule:
    - cron: '0 15 * * 5'  # 3 PM UTC every Friday
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:      # Corrected from paths_ignore
      - '**.md'       # Corrected quote syntax

permissions:
  contents: write

jobs:
  aggregate-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched for branch operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run aggregator
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python run_aggregator.py

      - name: Prepare gh-pages Branch
        if: success()
        run: |
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create or switch to gh-pages branch
          git checkout gh-pages || git checkout --orphan gh-pages

          # Remove all existing files
          git rm -rf .

          # Copy new build files from dist/ to root of gh-pages
          cp -R dist/* .

          # Add all files to Git
          git add .

          # Commit changes
          git commit -m "Update DevOps Weekly Update for $(date +'%Y-%m-%d')"

      - name: Push to gh-pages
        if: success()
        run: git push -f origin gh-pages
