name: DevOps News Aggregator
on:
  schedule:
    - cron: '0 15 * * 5'  # 3 PM UTC every Friday
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:      # Corrected from paths_ignore
      - '**.md'       # Corrected quote syntax

permissions:
  contents: write

jobs:
  aggregate-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run aggregator
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python main.py

      - name: Commit and push index.html to root of gh-pages branch
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages  # Create a new orphan gh-pages branch
          git reset --hard  # Clear any existing content in gh-pages branch
          cp dist/index.html ./index.html  # Copy index.html to root
          git add index.html
          git commit -m "Update index.html for DevOps News Aggregator"
          git push -f origin gh-pages  # Force push to gh-pages branch
